[package]
name = "sparkscan"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = { version = "0.3.31" }
progenitor-client = { version = "0.11.0" }
reqwest = { version = "0.12.20", features = ["json", "stream"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.140" }

[build-dependencies]
prettyplease = { version = "0.2.34" }
progenitor = { version = "0.11.0" }
serde_json = { version = "1.0.140" }
syn = { version = "2.0.103" }
